apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Core Cluster Infrastructure
  sourceRepos:
    - '*'
  destinations:
    # Разрешаем инфраструктурному проекту работать со всеми неймспейсами
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'