apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-gateway

helmCharts:
  - name: nginx-gateway-fabric
    repo: oci://ghcr.io/nginxinc/charts
    version: 2.4.1
    releaseName: ngf
    namespace: nginx-gateway
    includeCRDs: true