apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-frontend-api
  namespace: argocd
spec:
  project: infrastructure # Используем проект, который создавали ранее
  source:
    repoURL: 'https://github.com/denismironiuk/gitops-fleet.git' # НЕ ЗАБУДЬ СВОЙ URL
    targetRevision: main
    path: apps/overlays/prod/frontend-api
  destination:
    server: https://kubernetes.default.svc
    namespace: store-frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true