apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-infrastructure
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: 'https://github.com/denismironiuk/gitops-fleet.git' # ВАЖНО: твоя ссылка
    targetRevision: main
    path: infrastructure/overlays/prod-cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  # Указываем ArgoCD игнорировать системные инжекты Azure AKS
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: cert-manager-webhook
      jqPathExpressions:
        - '.webhooks[].namespaceSelector.matchExpressions'
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: cert-manager-webhook
      jqPathExpressions:
        - '.webhooks[].namespaceSelector.matchExpressions'